# Generated by Django 4.2.16 on 2025-01-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_project_projectimage_project_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="usage", field=models.CharField(max_length=255),
        ),
    ]
