# Generated by Django 4.2.16 on 2025-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_project_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="usage", field=models.CharField(max_length=255),
        ),
    ]
