# Generated by Django 4.2.16 on 2025-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_event_eventimage_event_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                ("phone", models.CharField(max_length=15)),
                ("email1", models.EmailField(blank=True, max_length=254, null=True)),
                ("email2", models.EmailField(blank=True, max_length=254, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Contact Me",},
        ),
    ]
